### ISSUE TITLE
RuntimeError： Attempting todeserialize object on a CUDA device but torch。cuda.is_available() is False。

### ISSUE THREAD

**Issue by 201402** [jackaduma/CycleGAN-VC2#10]

**Comment by 201402** [comment]
Sun Nov 22 11:02:56 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.100      Driver Version: 440.100      CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:01:00.0  On |                  N/A |
|  0%   26C    P8    18W / 300W |    305MiB / 11016MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1198      G   /usr/lib/xorg/Xorg                            24MiB |
|    0      1253      G   /usr/bin/gnome-shell                          58MiB |
|    0      3532      G   /usr/lib/xorg/Xorg                           129MiB |
|    0      3663      G   /usr/bin/gnome-shell                          89MiB |
+-----------------------------------------------------------------------------+

**Comment by keishatsai** [comment]
Have you try to specify the gpu device ?

**Comment by xianyanbao1** [comment]
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU. cuda 可以正常使用 为什么还报这个错误啊
